### ISSUE TITLE
mkdir /workspace/tmp/cache: permission denied

### ISSUE THREAD

**Issue by hovancik** [paketo-buildpacks/rails-assets#267]
## Expected Behavior

App deploys :) 

## Current Behavior

App does not deploy

## Possible Solution

Not sure. 

## Steps to Reproduce

Hi, I am using fly.io with the buildpack:

```
[build]
  builder = "paketobuildpacks/builder:full"
  buildpacks = ["gcr.io/paketo-buildpacks/ruby"]
```
I am getting error: 
```
mkdir /workspace/tmp/cache: permission denied
```
full log: 

```
===> DETECTING
10 of 12 buildpacks participating
paketo-buildpacks/ca-certificates 3.4.0
paketo-buildpacks/mri             0.8.10
paketo-buildpacks/bundler         0.5.10
paketo-buildpacks/bundle-install  0.5.8
paketo-buildpacks/node-engine     0.18.0
paketo-buildpacks/yarn            0.8.5
paketo-buildpacks/yarn-install    0.10.8
paketo-buildpacks/rails-assets    0.7.7
paketo-buildpacks/puma            0.4.7
paketo-buildpacks/procfile        5.4.0
===> ANALYZING
Previous image with name "registry.fly.io/lem:cache" not found
===> RESTORING
===> BUILDING

Paketo Buildpack for CA Certificates 3.4.0
  https://github.com/paketo-buildpacks/ca-certificates
  Launch Helper: Contributing to layer
    Creating /layers/paketo-buildpacks_ca-certificates/helper/exec.d/ca-certificates-helper
Paketo Buildpack for MRI 0.8.10
  Resolving MRI version
    Candidate version sources (in priority order):
      Gemfile   -> "3.1.2"
      <unknown> -> ""

    Selected MRI version (using Gemfile): 3.1.2

  Executing build process
    Installing MRI 3.1.2
      Completed in 2.86s

  Generating SBOM for /layers/paketo-buildpacks_mri/mri
      Completed in 0s

  Configuring build environment
    GEM_PATH -> "/home/cnb/.local/share/gem/ruby/3.1.0:/layers/paketo-buildpacks_mri/mri/lib/ruby/gems/3.1.0"

  Configuring launch environment
    GEM_PATH -> "/home/cnb/.local/share/gem/ruby/3.1.0:/layers/paketo-buildpacks_mri/mri/lib/ruby/gems/3.1.0"

Paketo Buildpack for Bundler 0.5.10
  Resolving Bundler version
    Candidate version sources (in priority order):
      Gemfile.lock -> "2.*.*"
      <unknown>    -> ""

    Selected Bundler version (using Gemfile.lock): 2.3.24

  Executing build process
    Installing Bundler 2.3.24
      Completed in 311ms

  Generating SBOM for /layers/paketo-buildpacks_bundler/bundler
      Completed in 0s

  Configuring build environment
    GEM_PATH -> "$GEM_PATH:/layers/paketo-buildpacks_bundler/bundler"

  Configuring launch environment
    GEM_PATH -> "$GEM_PATH:/layers/paketo-buildpacks_bundler/bundler"

Paketo Buildpack for Bundle Install 0.5.8
  Executing build environment install process
    Running 'bundle config --global clean true'
    Running 'bundle config --global path /layers/paketo-buildpacks_bundle-install/build-gems'
    Running 'bundle config --global cache_path --parseable'
      
    Running 'bundle install'
      Fetching gem metadata from https://rubygems.org/..........
      Fetching rake 13.0.6
      Installing rake 13.0.6
      Fetching concurrent-ruby 1.1.10
      Fetching minitest 5.16.3
      Fetching zeitwerk 2.6.0
      Fetching builder 3.2.4
      Installing builder 3.2.4
      Installing minitest 5.16.3
      Fetching erubi 1.11.0
      Installing zeitwerk 2.6.0
      Fetching mini_portile2 2.8.0
      Installing concurrent-ruby 1.1.10
      Using racc 1.6.0
      Fetching crass 1.0.6
      Installing erubi 1.11.0
      Fetching rack 2.2.4
      Installing mini_portile2 2.8.0
      Installing crass 1.0.6
      Installing rack 2.2.4
      Fetching websocket-extensions 0.1.5
      Fetching nio4r 2.5.8
      Installing websocket-extensions 0.1.5
      Fetching marcel 1.0.2
      Installing nio4r 2.5.8 with native extensions
      Fetching mini_mime 1.1.2
      Installing marcel 1.0.2
      Fetching public_suffix 5.0.0
      Installing mini_mime 1.1.2
      Fetching ast 2.4.2
      Installing ast 2.4.2
      Fetching bcrypt 3.1.18
      Fetching bindex 0.8.1
      Installing public_suffix 5.0.0
      Installing bindex 0.8.1 with native extensions
      Installing bcrypt 3.1.18 with native extensions
      Fetching msgpack 1.5.6
      Installing msgpack 1.5.6 with native extensions
      Fetching uniform_notifier 1.16.0
      Installing uniform_notifier 1.16.0
      Using bundler 2.3.24
      Fetching byebug 11.1.3
      Installing byebug 11.1.3 with native extensions
      Fetching matrix 0.4.2
      Installing matrix 0.4.2
      Fetching regexp_parser 2.5.0
      Installing regexp_parser 2.5.0
      Fetching chartkick 4.2.1
      Installing chartkick 4.2.1
      Fetching childprocess 4.1.0
      Installing childprocess 4.1.0
      Using digest 3.1.0
      Fetching docile 1.4.0
      Installing docile 1.4.0
      Fetching unf_ext 0.0.8.2
      Installing unf_ext 0.0.8.2 with native extensions
      Fetching dotenv 2.8.1
      Installing dotenv 2.8.1
      Fetching method_source 1.0.0
      Installing method_source 1.0.0
      Fetching thor 1.2.1
      Installing thor 1.2.1
      Fetching ffi 1.15.5
      Installing ffi 1.15.5 with native extensions
      Fetching http-accept 1.7.0
      Installing http-accept 1.7.0
      Fetching rb-fsevent 0.11.2
      Installing rb-fsevent 0.11.2
      Fetching mime-types-data 3.2022.0105
      Installing mime-types-data 3.2022.0105
      Fetching netrc 0.11.0
      Fetching timeout 0.3.0
      Installing netrc 0.11.0
      Installing timeout 0.3.0
      Fetching strscan 3.0.4
      Fetching pg 1.4.3
      Installing strscan 3.0.4 with native extensions
      Installing pg 1.4.3 with native extensions
      Fetching rexml 3.2.5
      Installing rexml 3.2.5
      Fetching rollbar 3.3.1
      Installing rollbar 3.3.1
      Fetching rubyzip 2.3.2
      Installing rubyzip 2.3.2
      Fetching websocket 1.2.9
      Installing websocket 1.2.9
      Fetching semantic_range 3.0.0
      Installing semantic_range 3.0.0
      Fetching simplecov-html 0.12.3
      Installing simplecov-html 0.12.3
      Fetching simplecov_json_formatter 0.1.4
      Installing simplecov_json_formatter 0.1.4
      Fetching spring 2.1.1
      Installing spring 2.1.1
      Fetching nokogiri 1.13.8
      Fetching websocket-driver 0.7.5
      Installing websocket-driver 0.7.5 with native extensions
      Installing nokogiri 1.13.8 with native extensions
      Fetching rack-test 2.0.2
      Installing rack-test 2.0.2
      Fetching rack-proxy 0.7.4
      Installing rack-proxy 0.7.4
      Fetching i18n 1.12.0
      Installing i18n 1.12.0
      Fetching tzinfo 2.0.5
      Installing tzinfo 2.0.5
      Fetching sprockets 4.1.1
      Installing sprockets 4.1.1
      Fetching parser 3.1.2.1
      Installing parser 3.1.2.1
      Fetching mail 2.7.1
      Installing mail 2.7.1
      Fetching addressable 2.8.1
      Installing addressable 2.8.1
      Fetching unf 0.1.4
      Installing unf 0.1.4
      Fetching mime-types 3.4.1
      Installing mime-types 3.4.1
      Fetching puma 5.6.5
      Installing puma 5.6.5 with native extensions
      Fetching net-protocol 0.1.3
      Installing net-protocol 0.1.3
      Fetching bootsnap 1.13.0
      Installing bootsnap 1.13.0 with native extensions
      Fetching selenium-webdriver 4.4.0
      Installing selenium-webdriver 4.4.0
      Fetching simplecov 0.21.2
      Installing simplecov 0.21.2
      Fetching scout_apm 5.3.1
      Fetching activesupport 6.1.7
      Installing activesupport 6.1.7
      Installing scout_apm 5.3.1 with native extensions
      Fetching domain_name 0.5.20190701
      Installing domain_name 0.5.20190701
      Fetching net-imap 0.2.3
      Installing net-imap 0.2.3
      Fetching net-pop 0.1.1
      Installing net-pop 0.1.1
      Fetching net-smtp 0.3.1
      Installing net-smtp 0.3.1
      Fetching rb-inotify 0.10.1
      Installing rb-inotify 0.10.1
      Fetching globalid 1.0.0
      Installing globalid 1.0.0
      Fetching activemodel 6.1.7
      Installing activemodel 6.1.7
      Fetching bullet 7.0.3
      Installing bullet 7.0.3
      Fetching delayed_job 4.1.10
      Installing delayed_job 4.1.10
      Fetching groupdate 6.1.0
      Installing groupdate 6.1.0
      Fetching http-cookie 1.0.5
      Installing http-cookie 1.0.5
      Fetching listen 3.7.1
      Installing listen 3.7.1
      Fetching activejob 6.1.7
      Installing activejob 6.1.7
      Fetching activerecord 6.1.7
      Installing activerecord 6.1.7
      Fetching rest-client 2.1.0
      Installing rest-client 2.1.0
      Fetching spring-watcher-listen 2.0.1
      Installing spring-watcher-listen 2.0.1
      Fetching delayed_job_active_record 4.1.7
      Installing delayed_job_active_record 4.1.7
      Fetching mailgun-ruby 1.2.5
      Fetching delayed_job_recurring 0.3.9
      Installing mailgun-ruby 1.2.5
      Installing delayed_job_recurring 0.3.9
      Fetching rails-dom-testing 2.0.3
      Fetching webdrivers 5.0.0
      Fetching xpath 3.2.0
      Fetching loofah 2.18.0
      Installing xpath 3.2.0
      Fetching capybara 3.37.1
      Installing capybara 3.37.1
      Installing webdrivers 5.0.0
      Installing loofah 2.18.0
      Fetching rails-html-sanitizer 1.4.3
      Installing rails-dom-testing 2.0.3
      Installing rails-html-sanitizer 1.4.3
      Fetching actionview 6.1.7
      Installing actionview 6.1.7
      Fetching actionpack 6.1.7
      Installing actionpack 6.1.7
      Fetching activestorage 6.1.7
      Fetching actionmailer 6.1.7
      Fetching railties 6.1.7
      Fetching actioncable 6.1.7
      Installing activestorage 6.1.7
      Installing actionmailer 6.1.7
      Installing actioncable 6.1.7
      Fetching sprockets-rails 3.4.2
      Fetching actionmailbox 6.1.7
      Installing railties 6.1.7
      Installing sprockets-rails 3.4.2
      Fetching actiontext 6.1.7
      Installing actionmailbox 6.1.7
      Installing actiontext 6.1.7
      Fetching web-console 4.2.0
      Fetching rails 6.1.7
      Fetching dotenv-rails 2.8.1
      Fetching webpacker 5.4.3
      Installing web-console 4.2.0
      Installing dotenv-rails 2.8.1
      Installing rails 6.1.7
      Installing webpacker 5.4.3
      Bundle complete! 28 Gemfile dependencies, 105 gems now installed.
      Bundled gems are installed into `/layers/paketo-buildpacks_bundle-install/build-gems`
      Post-install message from rubyzip:
      RubyZip 3.0 is coming!
      **********************
      
      The public API of some Rubyzip classes has been modernized to use named
      parameters for optional arguments. Please check your usage of the
      following classes:
        * `Zip::File`
        * `Zip::Entry`
        * `Zip::InputStream`
        * `Zip::OutputStream`
      
      Please ensure that your Gemfiles and .gemspecs are suitably restrictive
      to avoid an unexpected breakage when 3.0 is released (e.g. ~> 2.3.0).
      See https://github.com/rubyzip/rubyzip for details. The Changelog also
      lists other enhancements and bugfixes that have been implemented since
      version 2.3.0.
      Completed in 1m13.777s

  Generating SBOM for /layers/paketo-buildpacks_bundle-install/build-gems
      Completed in 359ms

  Executing launch environment install process
    Running 'bundle config --global clean true'
    Running 'bundle config --global path /layers/paketo-buildpacks_bundle-install/launch-gems'
    Running 'bundle config --global without development:test'
    Running 'bundle config --global cache_path --parseable'
      
    Running 'bundle install'
      Using rake 13.0.6
      Using concurrent-ruby 1.1.10
      Using i18n 1.12.0
      Using minitest 5.16.3
      Using tzinfo 2.0.5
      Using zeitwerk 2.6.0
      Using activesupport 6.1.7
      Using builder 3.2.4
      Using erubi 1.11.0
      Using mini_portile2 2.8.0
      Using racc 1.6.0
      Using nokogiri 1.13.8
      Using rails-dom-testing 2.0.3
      Using crass 1.0.6
      Using loofah 2.18.0
      Using rails-html-sanitizer 1.4.3
      Using actionview 6.1.7
      Using rack 2.2.4
      Using rack-test 2.0.2
      Using actionpack 6.1.7
      Using nio4r 2.5.8
      Using websocket-extensions 0.1.5
      Using websocket-driver 0.7.5
      Using actioncable 6.1.7
      Using globalid 1.0.0
      Using activejob 6.1.7
      Using activemodel 6.1.7
      Using activerecord 6.1.7
      Using marcel 1.0.2
      Using mini_mime 1.1.2
      Using activestorage 6.1.7
      Using mail 2.7.1
      Using actionmailbox 6.1.7
      Using actionmailer 6.1.7
      Using actiontext 6.1.7
      Using ast 2.4.2
      Using bcrypt 3.1.18
      Using msgpack 1.5.6
      Using bootsnap 1.13.0
      Using bundler 2.3.24
      Using chartkick 4.2.1
      Using delayed_job 4.1.10
      Using delayed_job_active_record 4.1.7
      Using delayed_job_recurring 0.3.9
      Using digest 3.1.0
      Using unf_ext 0.0.8.2
      Using unf 0.1.4
      Using domain_name 0.5.20190701
      Using groupdate 6.1.0
      Using http-accept 1.7.0
      Using http-cookie 1.0.5
      Using mime-types-data 3.2022.0105
      Using mime-types 3.4.1
      Using netrc 0.11.0
      Using rest-client 2.1.0
      Using mailgun-ruby 1.2.5
      Using method_source 1.0.0
      Using timeout 0.3.0
      Using net-protocol 0.1.3
      Using strscan 3.0.4
      Using net-imap 0.2.3
      Using net-pop 0.1.1
      Using net-smtp 0.3.1
      Using parser 3.1.2.1
      Using pg 1.4.3
      Using puma 5.6.5
      Using rack-proxy 0.7.4
      Using thor 1.2.1
      Using railties 6.1.7
      Using sprockets 4.1.1
      Using sprockets-rails 3.4.2
      Using rails 6.1.7
      Using rollbar 3.3.1
      Using scout_apm 5.3.1
      Using semantic_range 3.0.0
      Using webpacker 5.4.3
      Bundle complete! 28 Gemfile dependencies, 76 gems now installed.
      Gems in the groups 'development' and 'test' were not installed.
      Bundled gems are installed into `/layers/paketo-buildpacks_bundle-install/launch-gems`
      Removing addressable (2.8.1)
      Removing bindex (0.8.1)
      Removing bullet (7.0.3)
      Removing byebug (11.1.3)
      Removing capybara (3.37.1)
      Removing childprocess (4.1.0)
      Removing docile (1.4.0)
      Removing dotenv (2.8.1)
      Removing dotenv-rails (2.8.1)
      Removing ffi (1.15.5)
      Removing listen (3.7.1)
      Removing matrix (0.4.2)
      Removing public_suffix (5.0.0)
      Removing rb-fsevent (0.11.2)
      Removing rb-inotify (0.10.1)
      Removing regexp_parser (2.5.0)
      Removing rexml (3.2.5)
      Removing rubyzip (2.3.2)
      Removing selenium-webdriver (4.4.0)
      Removing simplecov (0.21.2)
      Removing simplecov-html (0.12.3)
      Removing simplecov_json_formatter (0.1.4)
      Removing spring (2.1.1)
      Removing spring-watcher-listen (2.0.1)
      Removing uniform_notifier (1.16.0)
      Removing web-console (4.2.0)
      Removing webdrivers (5.0.0)
      Removing websocket (1.2.9)
      Removing xpath (3.2.0)
      Completed in 1.399s

  Generating SBOM for /layers/paketo-buildpacks_bundle-install/launch-gems
      Completed in 354ms

  Configuring build environment
    BUNDLE_USER_CONFIG -> "/layers/paketo-buildpacks_bundle-install/build-gems/config"

  Configuring launch environment
    BUNDLE_USER_CONFIG -> "/layers/paketo-buildpacks_bundle-install/launch-gems/config"

Paketo Buildpack for Node Engine 0.18.0
  Resolving Node Engine version
    Candidate version sources (in priority order):
      package.json -> "16.17.1"
      <unknown>    -> ""

    Selected Node Engine version (using package.json): 16.17.1

  Executing build process
    Installing Node Engine 16.17.1
      Completed in 1.663s

  Generating SBOM for /layers/paketo-buildpacks_node-engine/node
      Completed in 0s

  Configuring build environment
    NODE_ENV     -> "production"
    NODE_HOME    -> "/layers/paketo-buildpacks_node-engine/node"
    NODE_VERBOSE -> "false"

  Configuring launch environment
    NODE_ENV     -> "production"
    NODE_HOME    -> "/layers/paketo-buildpacks_node-engine/node"
    NODE_VERBOSE -> "false"

    Writing exec.d/0-optimize-memory
      Calculates available memory based on container limits at launch time.
      Made available in the MEMORY_AVAILABLE environment variable.

Paketo Buildpack for Yarn 0.8.5
  Executing build process
    Installing Yarn
      Completed in 237ms

  Generating SBOM for /layers/paketo-buildpacks_yarn/yarn
      Completed in 0s

Paketo Buildpack for Yarn Install 0.10.8
  Resolving installation process
    Process inputs:
      yarn.lock -> Found

    Selected default build process: 'yarn install'

  Executing build environment install process
    Running yarn install --ignore-engines --frozen-lockfile --production false --modules-folder /layers/paketo-buildpacks_yarn-install/build-modules/node_modules
      Completed in 18.837s

  Configuring build environment
    NODE_ENV -> "development"
    PATH     -> "$PATH:/layers/paketo-buildpacks_yarn-install/build-modules/node_modules/.bin"

  Generating SBOM for /layers/paketo-buildpacks_yarn-install/build-modules
      Completed in 25.155s

mkdir /workspace/tmp/cache: permission denied
Paketo Buildpack for Rails Assets 0.7.7
ERROR: failed to build: exit status 1
Error failed to fetch an image or build from source: executing lifecycle: failed with status code: 51


```
## Motivations

Deploying the rails app with buildpack on fly.io

**Comment by sophiewigmore** [comment]
Also what does your app look like?

**Comment by hovancik** [comment]
@sophiewigmore sorry, got busy in last few months. 

Here's my PR with one of the apps where I try to implement this: https://github.com/hovancik/little_expense_manager/pull/131

I'm asking on Fly.io support here: https://community.fly.io/t/cant-build-rails-app-with-buildpacks/9748

**Comment by hovancik** [comment]
Also, just trying with heroku buildpacks, and seeing similar: 

```
rake aborted!
       Errno::EACCES: Permission denied @ dir_s_mkdir - /workspace/tmp/cache
       /workspace/vendor/bundle/ruby/3.1.0/gems/webpacker-5.4.3/lib/webpacker/compiler.rb:63:in `record_compilation_digest'
       /workspace/vendor/bundle/ruby/3.1.0/gems/webpacker-5.4.3/lib/webpacker/compiler.rb:28:in `block in compile'
       <internal:kernel>:90:in `tap'
       /workspace/vendor/bundle/ruby/3.1.0/gems/webpacker-5.4.3/lib/webpacker/compiler.rb:23:in `compile'
       /workspace/vendor/bundle/ruby/3.1.0/gems/webpacker-5.4.3/lib/webpacker/commands.rb:51:in `compile'
       /workspace/vendor/bundle/ruby/3.1.0/gems/webpacker-5.4.3/lib/webpacker.rb:35:in `compile'
       /workspace/vendor/bundle/ruby/3.1.0/gems/webpacker-5.4.3/lib/tasks/webpacker/compile.rake:23:in `block (4 levels) in <main>'
       /workspace/vendor/bundle/ruby/3.1.0/gems/webpacker-5.4.3/lib/webpacker.rb:28:in `ensure_log_goes_to_stdout'
       /workspace/vendor/bundle/ruby/3.1.0/gems/webpacker-5.4.3/lib/tasks/webpacker/compile.rake:22:in `block (3 levels) in <main>'
       /workspace/vendor/bundle/ruby/3.1.0/gems/webpacker-5.4.3/lib/webpacker.rb:20:in `with_node_env'
       /workspace/vendor/bundle/ruby/3.1.0/gems/webpacker-5.4.3/lib/tasks/webpacker/compile.rake:21:in `block (2 levels) in <main>'
       Tasks: TOP => assets:precompile => webpacker:compile
       (See full trace by running task with --trace)
```

**Comment by ryanmoran** [comment]
By default, when running in production, Rails will choose to use an `ActiveSupport::Cache::FileStore` with a default path to `#{root}/tmp/cache/`. Since the `/workspace` directory of the application is read-only for the Rails process, you'll get a permission denied error when you attempt to run the application.

You have a couple of options:
1. Switch to a cache store that doesn't rely on the filesystem, like `MemoryStore` or `RedisCacheStore`. These options have their own tradeoffs and complexities. You should read the docs to understand the choices here better: https://guides.rubyonrails.org/v6.1/caching_with_rails.html#cache-stores
2. You can configure the cache file store to use a writable location on disk by including the following configuration in your `config/environments/production.rb` file.
   ```
   config.cache_store = :file_store, "/path/to/a/writable/directory"
   ``` 
   I don't know about fly.io specifically, but often the `/tmp` directory has permissions that make it broadly writable.

**Comment by hovancik** [comment]
@ryanmoran I'm trying to set `config.cache_store` as you mentioned, but it does not have any effect and I am getting the same error

**Comment by hovancik** [comment]
I mean the location has not changed and the error still says `/workspace/tmp/cache`

**Comment by hovancik** [comment]
I also found cache config option for production with `webpacker.yml` and set it to `  cache_path: /tmp` but no effect and same error. Not sure why that has no effect.

**Comment by ryanmoran** [comment]
I'm having trouble reproducing this. I'm running the following on the `feature/paketo` branch of your repo:

```
pack build lemur --builder paketobuildpacks/builder:full --buildpack paketo-buildpacks/ruby --env SECRET_KEY_BASE=1
```

I can then run it with the following:
```
docker run -it -p 3000:3000 --env SECRET_KEY_BASE=1 lemur
```

And see it in the browser:
![Screen Shot 2023-01-10 at 8 13 43 AM](https://user-images.githubusercontent.com/155736/211604057-b6e2c568-4786-4837-afa8-d8ddaaf2d86d.png)

**Comment by hovancik** [comment]
Must be then something with Fly.io, but I have no reply from them. 

Thanks for trying to help!
